mlb_app/info/urls.py
from django.urls import path, include
from . import views

app_name = 'info'

urlpatterns = [
    path('', views.home, name="home"),
    path('search_player', views.search_player, name="search_player"),
    path('player_detail', views.player_detail, name="get_player_detail"),
]

mlb_app/mlb_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('info/', include('info.urls')),
]

mlb_app/info/models.py
from django.db import models

# Create your models here.

mlb_app/info/views.py
from django.http import response
from django.shortcuts import render
import requests

def home(request):
    return render(request, 'home.html')

def search_player(request):
    if request.method == "GET":
        query = request.GET.get("q")
        r = requests.get(f"http://lookup-service-prod.mlb.com/json/named.search_player_all.bam?sport_code='mlb'&active_sw='Y'&name_part='{query}%25'")
        response = r.json()['search_player_all']['queryResults']['row']
        print(response)
        player_list = []
        for player in response:
            result = {'name': player['name_display_first_last'], 'team': player['team_full'], 'id': player['player_id']}
            player_list.append(result)
    return render(request, 'search_player.html', {'players': player_list})

def player_detail(request, player_id):
    id = int(player_id['player_id'])
    player_detail = f"http://lookup-service-prod.mlb.com/json/named.player_info.bam?sport_code='mlb'&player_id={id}"
    r = requests.get(player_detail)
    response = r.json()
    content = {
        'name': response['search_player_all']['queryResults']['row']['name_display_first_last_html'],
        'number': response['search_player_all']['queryResults']['row']['jersey_number'],
        'team_full': response['search_player_all']['queryResults']['row']['team_full'],
        'position': response['search_player_all']['queryResults']['row']['position'],
        'bats': response['search_player_all']['queryResults']['row']['bats'],
        'throws': response['search_player_all']['queryResults']['row']['throws'],
        'birth_country': response['search_player_all']['queryResults']['row']['birth_country'],
        'birth_date': response['search_player_all']['queryResults']['row']['birth_date'],
        'height_feet': response['search_player_all']['queryResults']['row']['height_feet'],
        'height_inches': response['search_player_all']['queryResults']['row']['height_inches'],
        'age': response['search_player_all']['queryResults']['row']['age']
    }
    return render(request, 'player_detail.html', content)

mlb_app/templates/home.html
{% block content %}

<form class="d-flex" type="get" action="{% url 'info:search_player' %}">
  <input class="form-control me-2" type="search" id="q" name="q" placeholder="Search Player by Last Name"
    aria-label="Search">
  <button class="btn btn-outline-success" type="submit">Search</button>
</form>

{% endblock %}

mlb_app/templates/player_detail.html
{% block content %}

<div>
  <h1>Name: {{name}}</h1>
  <h4>Jersey Number: {{number}}</h4>
  <h4>Team: {{team_full}}</h4>
  <h4>Position: {{position}}</h4>
  <h4>Bats: {{bats}}</h4>
  <h4>Throws: {{throws}}</h4>
  <h4>Height: {{height_feet}}' {{height_inches}}"</h4>
  <h4>Age: {{age}}</h4>
</div>

{% endblock %}

mlb_app/templates/search_player.html
{% block content %}

{% for player in players %}

<h1>
  Name: {{player.name}}
</h1>
<h4>Team: {{player.team}}</h4>
<h4>ID: {{player.id}}</h4>
{% endfor %}

{% endblock %}